---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-management-service
  title: User Management Service by Choreo Integrations Team
  description: A RESTful API for user authentication, authorization, and profile management.
  tags:
    - backend
    - service
    - authentication
    - authorization
spec:
  type: service
  lifecycle: experimental
  owner: choreo-integrations-team
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-react
  title: To-do in React
  description: A web-based To-do application, written in React. For demonstration purposes only!
  tags:
    - react
    - website
spec:
  type: service
  lifecycle: experimental
  owner: integrations-team
